# local machine configuration file

general:
    timezone: Asia/Singapore

database:
    host: localhost 
    username: root
    password:
    name: rubik


admin:
    maintenance: false
    debug: true
    landing_module: /history
    timezone: 


www:
    maintenance: false
    debug: false


cli:


api:


