# localhost configuration file

DATABASE:
    host: localhost
    username: ##AUTO_REPLACE_DB_USERNAME##
    password: ##AUTO_REPLACE_DB_PASSWORD##
    name: ##AUTO_REPLACE_DB_NAME##

SITE:
    name: Test
    description: Test CMS

GENERAL:
    maintenance: false  

