# localhost configuration file

database:
    host: localhost
    username: %database_username%
    password: %database_password%
    name: %database_name%

site:
    name: Test
    description: Test CMS

general:
    maintenance: false  

